localrules: generate_hmmscan_commands

## Global variables
PFAM = '../data/pfam_hmm_lib/Pfam-A.hmm'
ORTHOGROUP_SEQUENCES = '../data/Orthogroup_Sequences_test'
HMMSCAN_COMMANDS = '../resources/hmmscan_commands'
HMMSCAN_OUTPUTS = \
    expand("../results/hmmscan/{og}",
           og=glob_wildcards("../data/Orthogroup_Sequences_test/{og}.fa")[0])

################################################################################

rule all:
    input: HMMSCAN_OUTPUTS

rule clean:
    shell: "rm -r {HMMSCAN_COMMANDS} {HMMSCAN_OUTPUTS}"

rule generate_hmmscan_commands:
    """Produces text file of hmmscan commands to run, to generate hmmscan
    Pfam domain assignments for all orthogroups.
    
    Writing text file of hmmscan commands allows us to run all these commands
    in parallel to speed things up.
    """
    input: ORTHOGROUP_SEQUENCES
    output: HMMSCAN_COMMANDS
    shell: "python scripts/generate_hmmscan_commands.py {input} {output} {PFAM}"

rule run_hmmscan:
    input: HMMSCAN_COMMANDS
    output: HMMSCAN_OUTPUTS
    shell: "mkdir -p ../results/hmmscan && parallel < {input}"